version: "3.8"
services:
  db:
    container_name: notice_db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password1234!
      - MYSQL_ROOT_PASSWORD=password1234!
      - MYSQL_DATABASE=study_db
